<template><div><p>제가 Kotlin에서 브라우저의 기본 JS 객체를 사용할 수 있도록 'external'을 사용하여 다양한 래핑을 만들었어요.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>external <span class="token keyword">interface</span> <span class="token class-name">JsMap</span><span class="token punctuation">{</span>
    fun <span class="token function">has</span><span class="token punctuation">(</span>key<span class="token operator">:</span>dynamic<span class="token punctuation">)</span><span class="token operator">:</span>Boolean
    fun <span class="token function">get</span><span class="token punctuation">(</span>key<span class="token operator">:</span>dynamic<span class="token punctuation">)</span><span class="token operator">:</span>dynamic
    fun <span class="token function">set</span><span class="token punctuation">(</span>key<span class="token operator">:</span>dynamic<span class="token punctuation">,</span> <span class="token literal-property property">value</span><span class="token operator">:</span>dynamic<span class="token punctuation">)</span>
    fun <span class="token keyword">delete</span><span class="token punctuation">(</span>key<span class="token operator">:</span>dynamic<span class="token punctuation">)</span>
<span class="token punctuation">}</span>

external <span class="token keyword">interface</span> <span class="token class-name">JsArray</span><span class="token operator">&lt;</span><span class="token constant">V</span><span class="token operator">:</span>Any<span class="token operator">></span><span class="token punctuation">{</span>
    operator fun <span class="token function">get</span><span class="token punctuation">(</span>i<span class="token operator">:</span>Int<span class="token punctuation">)</span><span class="token operator">:</span><span class="token constant">V</span><span class="token operator">?</span>
    operator fun <span class="token function">set</span><span class="token punctuation">(</span>i<span class="token operator">:</span>Int<span class="token punctuation">,</span> <span class="token literal-property property">v</span><span class="token operator">:</span><span class="token constant">V</span><span class="token punctuation">)</span>
    val length<span class="token operator">:</span>Int
    fun <span class="token function">push</span><span class="token punctuation">(</span>vararg v<span class="token operator">:</span><span class="token constant">V</span><span class="token punctuation">)</span>
    fun <span class="token function">forEach</span><span class="token punctuation">(</span>block<span class="token operator">:</span><span class="token punctuation">(</span><span class="token constant">V</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>Unit<span class="token punctuation">)</span>
    fun <span class="token operator">&lt;</span><span class="token constant">TO</span><span class="token operator">:</span>Any<span class="token operator">></span> <span class="token function">map</span><span class="token punctuation">(</span>block<span class="token operator">:</span><span class="token punctuation">(</span><span class="token constant">V</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token constant">TO</span><span class="token punctuation">)</span><span class="token operator">:</span>JsArray<span class="token operator">&lt;</span><span class="token constant">TO</span><span class="token operator">></span>
    fun <span class="token function">any</span><span class="token punctuation">(</span>block<span class="token operator">:</span><span class="token punctuation">(</span><span class="token constant">V</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>Boolean<span class="token punctuation">)</span><span class="token operator">:</span>Boolean
    fun <span class="token function">all</span><span class="token punctuation">(</span>block<span class="token operator">:</span><span class="token punctuation">(</span><span class="token constant">V</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>Boolean<span class="token punctuation">)</span><span class="token operator">:</span>Boolean
    fun <span class="token function">indexOf</span><span class="token punctuation">(</span>v<span class="token operator">:</span><span class="token constant">V</span><span class="token punctuation">)</span><span class="token operator">:</span>Int
    fun <span class="token function">filter</span><span class="token punctuation">(</span>block<span class="token operator">:</span><span class="token punctuation">(</span><span class="token constant">V</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>Boolean<span class="token punctuation">)</span><span class="token operator">:</span>JsArray<span class="token operator">&lt;</span><span class="token constant">V</span><span class="token operator">></span>
    fun <span class="token function">slice</span><span class="token punctuation">(</span>start<span class="token operator">:</span>Int<span class="token punctuation">,</span> <span class="token literal-property property">end</span><span class="token operator">:</span>Int <span class="token operator">=</span> definedExternally<span class="token punctuation">)</span><span class="token operator">:</span>JsArray<span class="token operator">&lt;</span><span class="token constant">V</span><span class="token operator">></span>
    fun <span class="token function">splice</span><span class="token punctuation">(</span>start<span class="token operator">:</span>Int<span class="token punctuation">,</span> <span class="token literal-property property">deleteCount</span><span class="token operator">:</span>Int<span class="token punctuation">,</span> vararg items<span class="token operator">:</span><span class="token constant">V</span><span class="token punctuation">)</span><span class="token operator">:</span>JsArray<span class="token operator">&lt;</span><span class="token constant">V</span><span class="token operator">></span>
<span class="token punctuation">}</span>

external <span class="token keyword">interface</span> <span class="token class-name">JsObject</span><span class="token punctuation">{</span>
    operator fun <span class="token function">get</span><span class="token punctuation">(</span>key<span class="token operator">:</span>String<span class="token punctuation">)</span><span class="token operator">:</span>dynamic
    operator fun <span class="token function">set</span><span class="token punctuation">(</span>key<span class="token operator">:</span>String<span class="token punctuation">,</span> <span class="token literal-property property">value</span><span class="token operator">:</span>dynamic<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>실제로 브라우저에 JsArray가 존재하지는 않지만, Kotlin이 인식할 수 있는 타입이 필요하기 때문에 선언되었어요. 실질적인 강점은 Kotlin 객체를 JS로 전달하거나 JS에서 Kotlin으로 객체를 받을 때 나타납니다.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>inline fun <span class="token operator">&lt;</span><span class="token constant">K</span><span class="token operator">:</span>Any<span class="token punctuation">,</span> <span class="token constant">V</span><span class="token operator">:</span>Any<span class="token operator">></span> Map<span class="token operator">&lt;</span><span class="token constant">K</span><span class="token punctuation">,</span> <span class="token constant">V</span><span class="token operator">></span><span class="token punctuation">.</span><span class="token function">toJsMap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span>JsMap 
<span class="token operator">=</span> <span class="token function">js</span><span class="token punctuation">(</span><span class="token string">"new Map()"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>also <span class="token punctuation">{</span>map<span class="token operator">-</span><span class="token operator">></span>
    forEach <span class="token punctuation">{</span><span class="token punctuation">(</span>k<span class="token punctuation">,</span> v<span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span> map<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span>k<span class="token punctuation">,</span> v<span class="token punctuation">)</span><span class="token punctuation">}</span>
<span class="token punctuation">}</span> <span class="token keyword">as</span> JsMap

inline fun <span class="token operator">&lt;</span><span class="token constant">K</span><span class="token operator">:</span>Any<span class="token punctuation">,</span> <span class="token constant">V</span><span class="token operator">:</span>Any<span class="token operator">></span> Map<span class="token operator">&lt;</span><span class="token constant">K</span><span class="token punctuation">,</span> <span class="token constant">V</span><span class="token operator">></span><span class="token punctuation">.</span><span class="token function">toJsObject</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span>JsObject 
<span class="token operator">=</span> <span class="token function">js</span><span class="token punctuation">(</span><span class="token string">"Object.create(null)"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>also<span class="token punctuation">{</span>obj<span class="token operator">-</span><span class="token operator">></span> 
    forEach<span class="token punctuation">{</span><span class="token punctuation">(</span>k<span class="token punctuation">,</span> v<span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>obj<span class="token punctuation">[</span>k<span class="token punctuation">]</span> <span class="token operator">=</span> v<span class="token punctuation">}</span>
<span class="token punctuation">}</span> <span class="token keyword">as</span> JsObject

inline fun <span class="token operator">&lt;</span><span class="token constant">V</span><span class="token operator">:</span>Any<span class="token operator">></span> Iterable<span class="token operator">&lt;</span><span class="token constant">V</span><span class="token operator">></span><span class="token punctuation">.</span><span class="token function">toJsArray</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span>JsArray<span class="token operator">&lt;</span><span class="token constant">V</span><span class="token operator">></span> 
<span class="token operator">=</span> <span class="token function">js</span><span class="token punctuation">(</span><span class="token string">"[]"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>also <span class="token punctuation">{</span>arr<span class="token operator">-</span><span class="token operator">></span>
    forEachIndexed <span class="token punctuation">{</span>index<span class="token punctuation">,</span> v<span class="token operator">-</span><span class="token operator">></span> arr<span class="token punctuation">[</span>index<span class="token punctuation">]</span> <span class="token operator">=</span> v<span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><!-- ui-log 수평형 -->
<p><ins class="adsbygoogle"
  style="display:block"
  data-ad-client="ca-pub-4877378276818686"
  data-ad-slot="9743150776"
  data-ad-format="auto"
  data-full-width-responsive="true"></ins></p>
<component is="script">
(adsbygoogle = window.adsbygoogle || []).push({});
</component>
<p>실제 변환 작업은 브라우저에서 자연스럽게 통합되도록 js(..) 함수를 통해 실제 JS 객체를 생성하여 수행됩니다.</p>
<p>JS 객체에 대한 확장 기능을 정의하는 것도 쉽습니다. 예를 들어, 'delete obj[key]'는 'Reflect.deleteProperty(obj, key)'로 대체할 수 있습니다. 이를 JsObject의 'delete' 확장 기능으로도 정의할 수 있습니다.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>external <span class="token keyword">class</span> <span class="token class-name">Reflect</span><span class="token punctuation">{</span>
    companion object <span class="token punctuation">{</span>
        fun <span class="token function">deleteProperty</span><span class="token punctuation">(</span>target<span class="token operator">:</span>Any<span class="token punctuation">,</span> <span class="token literal-property property">propertyKey</span><span class="token operator">:</span>String<span class="token punctuation">)</span><span class="token operator">:</span>Boolean
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

inline fun JsObject<span class="token punctuation">.</span><span class="token function">delete</span><span class="token punctuation">(</span>key<span class="token operator">:</span>String<span class="token punctuation">)</span><span class="token operator">:</span>Boolean 
<span class="token operator">=</span> Reflect<span class="token punctuation">.</span><span class="token function">deleteProperty</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> key<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>마지막으로 살펴볼 사례는 Kotlin에서 인라인의 reified 기능을 사용하여 T 유형의 ::class를 키로 사용하는 Map을 생성하는 것이 일반적이라는 것입니다.</p>
<!-- ui-log 수평형 -->
<p><ins class="adsbygoogle"
  style="display:block"
  data-ad-client="ca-pub-4877378276818686"
  data-ad-slot="9743150776"
  data-ad-format="auto"
  data-full-width-responsive="true"></ins></p>
<component is="script">
(adsbygoogle = window.adsbygoogle || []).push({});
</component>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">val</span> map<span class="token operator">:</span> HashMap<span class="token operator">&lt;</span>KClass<span class="token operator">&lt;</span><span class="token operator">*</span><span class="token operator">></span><span class="token punctuation">,</span> Int<span class="token operator">></span> <span class="token operator">=</span> <span class="token function">hashMapOf</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

<span class="token keyword">inline</span> <span class="token keyword">fun</span> <span class="token operator">&lt;</span><span class="token keyword">reified</span> T <span class="token operator">:</span> Any<span class="token operator">></span> <span class="token function">add</span><span class="token punctuation">(</span><span class="token keyword">data</span><span class="token operator">:</span> Int<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    map<span class="token punctuation">[</span>T<span class="token operator">::</span><span class="token keyword">class</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token keyword">data</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>만약 KClass 대신 고유 식별자 문자열을 사용하고 싶다면 qualifiedName을 사용할 수 있습니다. 이 속성은 일반적으로 동일한 응용 프로그램 도메인 내에서만 유효하기 때문에 충분한 식별을 제공합니다.</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">val</span> map<span class="token operator">:</span> HashMap<span class="token operator">&lt;</span>String<span class="token punctuation">,</span> Int<span class="token operator">></span> <span class="token operator">=</span> <span class="token function">hashMapOf</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

<span class="token keyword">inline</span> <span class="token keyword">fun</span> <span class="token operator">&lt;</span><span class="token keyword">reified</span> T <span class="token operator">:</span> Any<span class="token operator">></span> <span class="token function">add</span><span class="token punctuation">(</span><span class="token keyword">data</span><span class="token operator">:</span> Int<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    map<span class="token punctuation">[</span>T<span class="token operator">::</span><span class="token keyword">class</span><span class="token punctuation">.</span>qualifiedName<span class="token operator">!!</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token keyword">data</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>그러나 문제는 kotlinJS가 simpleName만 지원하고 qualifiedName은 지원하지 않는다는 것입니다. 한편, kotlinJS가 단일 스레드 환경에서 작동하기 때문에 동기화 문제가 없다는 장점을 살릴 수 있습니다.</p>
<!-- ui-log 수평형 -->
<p><ins class="adsbygoogle"
  style="display:block"
  data-ad-client="ca-pub-4877378276818686"
  data-ad-slot="9743150776"
  data-ad-format="auto"
  data-full-width-responsive="true"></ins></p>
<component is="script">
(adsbygoogle = window.adsbygoogle || []).push({});
</component>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">private</span> <span class="token keyword">var</span> kClassId<span class="token operator">:</span>Int <span class="token operator">=</span> <span class="token number">0</span>
<span class="token keyword">private</span> <span class="token keyword">val</span> kClassIdMap<span class="token operator">:</span>HashMap<span class="token operator">&lt;</span>KClass<span class="token operator">&lt;</span><span class="token operator">*</span><span class="token operator">></span><span class="token punctuation">,</span> String<span class="token operator">></span> <span class="token operator">=</span> <span class="token function">hashMapOf</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

<span class="token keyword">val</span> <span class="token operator">&lt;</span>T<span class="token operator">:</span>Any<span class="token operator">></span> KClass<span class="token operator">&lt;</span>T<span class="token operator">></span><span class="token punctuation">.</span>id<span class="token operator">:</span>String 
  <span class="token keyword">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span> kClassIdMap<span class="token punctuation">.</span><span class="token function">getOrPut</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token string-literal singleline"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">simpleName</span></span><span class="token string">|</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">kClassId<span class="token operator">++</span></span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>위의 코드는 각 KClass마다 고유한 식별자를 만들어 simpleName에 고유한 숫자 ID를 추가합니다. 이를 위해 KClass에 'id'라는 확장 속성을 사용하여 하나의 KClass에 대해 한 번만 고유한 식별자가 생성되도록 합니다.</p>
<p>이를 활용하여 위의 예제를 다음과 같이 수정할 수 있습니다.</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">val</span> map<span class="token operator">:</span>HashMap<span class="token operator">&lt;</span>String<span class="token punctuation">,</span> Int<span class="token operator">></span> <span class="token operator">=</span> <span class="token function">hashMapOf</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

<span class="token keyword">inline</span> <span class="token keyword">fun</span> <span class="token operator">&lt;</span><span class="token keyword">reified</span> T<span class="token operator">:</span>Any<span class="token operator">></span> <span class="token function">add</span><span class="token punctuation">(</span><span class="token keyword">data</span><span class="token operator">:</span>Int<span class="token punctuation">)</span><span class="token punctuation">{</span>
    map<span class="token punctuation">[</span>T<span class="token operator">::</span><span class="token keyword">class</span><span class="token punctuation">.</span>id<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token keyword">data</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><!-- ui-log 수평형 -->
<p><ins class="adsbygoogle"
  style="display:block"
  data-ad-client="ca-pub-4877378276818686"
  data-ad-slot="9743150776"
  data-ad-format="auto"
  data-full-width-responsive="true"></ins></p>
<component is="script">
(adsbygoogle = window.adsbygoogle || []).push({});
</component>
<p>오늘의 기록은 여기까지에요.</p>
</div></template>
