<template><div><p>Storybook은 Webpack, Vite 및 ESBuild를 포함한 여러 빌더를 지원하는 구조로 설계되어 있습니다. 빌더 API는 Storybook에 새로운 빌더를 추가할 수 있는 인터페이스 세트입니다.</p>
<p><img src="@source/docs/Tech/2024-04-07-BuilderAPI/img/BuilderAPI_0.png" alt="BuilderAPI_0.png"></p>
<h2 id="빌더는-어떻게-작동하나요" tabindex="-1"><a class="header-anchor" href="#빌더는-어떻게-작동하나요" aria-hidden="true">#</a> 빌더는 어떻게 작동하나요?</h2>
<p>Storybook에서 빌더는 컴포넌트와 이야기를 브라우저에서 실행되는 JS 번들로 컴파일하는 역할을 합니다. 빌더는 인터랙티브 개발을 위한 개발 서버뿐만 아니라 최적화된 번들을 위한 프로덕션 모드도 제공합니다.</p>
<p>빌더를 선택하려면 사용자는 종속성으로 추가한 후 구성 파일(.storybook/main.js)을 편집하여 활성화해야 합니다. 예를 들어, Vite 빌더를 사용하는 경우:</p>
<div class="language-npm ext-npm line-numbers-mode"><pre v-pre class="language-npm"><code>npm install @storybook/builder-vite --save-dev
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
  stories<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'../src/**/*.mdx'</span><span class="token punctuation">,</span> <span class="token string">'../stories/**/*.stories.@(js|jsx|mjs|ts|tsx)'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
  addons<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'@storybook/addon-links'</span><span class="token punctuation">,</span> <span class="token string">'@storybook/addon-essentials'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
  core<span class="token operator">:</span> <span class="token punctuation">{</span>
    builder<span class="token operator">:</span> <span class="token string">'@storybook/builder-vite'</span><span class="token punctuation">,</span> <span class="token comment">// 👈 여기서 빌더를 활성화합니다.</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="빌더-api" tabindex="-1"><a class="header-anchor" href="#빌더-api" aria-hidden="true">#</a> 빌더 API</h2>
<p>Storybook에서는 모든 빌더가 다음 API를 구현해야 하며, 다음 구성 옵션과 진입 지점을 노출해야 합니다:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">export</span> <span class="token keyword">interface</span> <span class="token class-name">Builder<span class="token operator">&lt;</span>Config<span class="token punctuation">,</span> Stats<span class="token operator">></span></span> <span class="token punctuation">{</span>
  <span class="token function-variable function">start</span><span class="token operator">:</span> <span class="token punctuation">(</span>args<span class="token operator">:</span> <span class="token punctuation">{</span>
    options<span class="token operator">:</span> Options<span class="token punctuation">;</span>
    startTime<span class="token operator">:</span> ReturnType<span class="token operator">&lt;</span><span class="token keyword">typeof</span> process<span class="token punctuation">.</span>hrtime<span class="token operator">></span><span class="token punctuation">;</span>
    router<span class="token operator">:</span> Router<span class="token punctuation">;</span>
    server<span class="token operator">:</span> Server<span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span><span class="token keyword">void</span> <span class="token operator">|</span> <span class="token punctuation">{</span>
    stats<span class="token operator">?</span><span class="token operator">:</span> Stats<span class="token punctuation">;</span>
    totalTime<span class="token operator">:</span> ReturnType<span class="token operator">&lt;</span><span class="token keyword">typeof</span> process<span class="token punctuation">.</span>hrtime<span class="token operator">></span><span class="token punctuation">;</span>
    <span class="token function-variable function">bail</span><span class="token operator">:</span> <span class="token punctuation">(</span>e<span class="token operator">?</span><span class="token operator">:</span> Error<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span><span class="token keyword">void</span><span class="token operator">></span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token operator">></span><span class="token punctuation">;</span>
  <span class="token function-variable function">build</span><span class="token operator">:</span> <span class="token punctuation">(</span>arg<span class="token operator">:</span> <span class="token punctuation">{</span>
    options<span class="token operator">:</span> Options<span class="token punctuation">;</span>
    startTime<span class="token operator">:</span> ReturnType<span class="token operator">&lt;</span><span class="token keyword">typeof</span> process<span class="token punctuation">.</span>hrtime<span class="token operator">></span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span><span class="token keyword">void</span> <span class="token operator">|</span> Stats<span class="token operator">></span><span class="token punctuation">;</span>
  <span class="token function-variable function">bail</span><span class="token operator">:</span> <span class="token punctuation">(</span>e<span class="token operator">?</span><span class="token operator">:</span> Error<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span><span class="token keyword">void</span><span class="token operator">></span><span class="token punctuation">;</span>
  <span class="token function-variable function">getConfig</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token operator">:</span> Options<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>Config<span class="token operator">></span><span class="token punctuation">;</span>
  corePresets<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  overridePresets<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>개발 모드에서 start API 호출은 개발 서버를 초기화하여 파일 시스템 변경 사항(예: 컴포넌트 및 스토리)을 모니터링한 후 브라우저에서 핫 모듈 리로드를 실행하는 것을 담당합니다. 또한 사용자 입력 또는 오류를 통해 실행 프로세스를 안전하게 종료하기 위한 bail 함수를 제공합니다.</p>
<p>프로덕션에서 build API 호출은 정적 Storybook 빌드를 생성하는 것을 담당하며, 추가 구성이 제공되지 않는 경우 기본적으로 storybook-static 디렉토리에 저장합니다. 생성된 출력물은 사용자가 인덱스.html 또는 iframe.html을 열어 Storybook을 보는 데 필요한 모든 것을 포함해야 하며, 다른 프로세스가 실행되고 있지 않은 상태에서 브라우저에서 열 수 있어야 합니다.</p>
<h2 id="구현" tabindex="-1"><a class="header-anchor" href="#구현" aria-hidden="true">#</a> 구현</h2>
<p>내부적으로 빌더는 미리보기 iframe을 제공하거나 구축하는 역할을 맡고 있습니다. 미리보기 iframe은 별도의 요구 사항을 갖고 있습니다. Storybook과 함께 제공되는 Essential 애드온을 완전히 지원하려면 다음 사항을 고려해야 합니다.</p>
<h3 id="스토리-가져오기" tabindex="-1"><a class="header-anchor" href="#스토리-가져오기" aria-hidden="true">#</a> 스토리 가져오기</h3>
<p>스토리 설정 필드는 Storybook에서 스토리를 로딩하는 데 사용됩니다. 구성은 컴포넌트의 스토리의 물리적 위치를 포함하는 파일 글로브 배열을 정의합니다. 빌더는 해당 파일을 로드하고 변경 사항을 모니터링하고 UI를 업데이트할 수 있어야 합니다.</p>
<h3 id="구성-옵션-제공" tabindex="-1"><a class="header-anchor" href="#구성-옵션-제공" aria-hidden="true">#</a> 구성 옵션 제공</h3>
<p>기본적으로 Storybook의 구성은 별도의 파일 (storybook/main.js|ts)에서 처리되어 사용자가 필요에 맞게 사용자 정의할 수 있는 옵션을 제공합니다. 빌더는 추가 필드 또는 다른 빌더에 적합한 메커니즘을 통해 자체 구성 지원도 제공해야 합니다. 예를 들어:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> stringifyProcessEnvs <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./envs'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> getOptimizeDeps <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./optimizeDeps'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> commonConfig <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./vite-config'</span><span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token keyword">type</span> <span class="token punctuation">{</span> EnvsRaw<span class="token punctuation">,</span> ExtendedOptions <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./types'</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">async</span> <span class="token keyword">function</span> <span class="token function">createViteServer</span><span class="token punctuation">(</span>options<span class="token operator">:</span> ExtendedOptions<span class="token punctuation">,</span> devServer<span class="token operator">:</span> Server<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> <span class="token punctuation">{</span> port<span class="token punctuation">,</span> presets <span class="token punctuation">}</span> <span class="token operator">=</span> options<span class="token punctuation">;</span>

  <span class="token comment">// Defines the baseline config.</span>
  <span class="token keyword">const</span> baseConfig <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">commonConfig</span><span class="token punctuation">(</span>options<span class="token punctuation">,</span> <span class="token string">'development'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> defaultConfig <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>baseConfig<span class="token punctuation">,</span>
    server<span class="token operator">:</span> <span class="token punctuation">{</span>
      middlewareMode<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
      hmr<span class="token operator">:</span> <span class="token punctuation">{</span>
        port<span class="token punctuation">,</span>
        server<span class="token operator">:</span> devServer<span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
      fs<span class="token operator">:</span> <span class="token punctuation">{</span>
        strict<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    optimizeDeps<span class="token operator">:</span> <span class="token keyword">await</span> <span class="token function">getOptimizeDeps</span><span class="token punctuation">(</span>baseConfig<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>

  <span class="token keyword">const</span> finalConfig <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">presets</span><span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span><span class="token string">'viteFinal'</span><span class="token punctuation">,</span> defaultConfig<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">const</span> envsRaw <span class="token operator">=</span> <span class="token keyword">await</span> presets<span class="token punctuation">.</span><span class="token generic-function"><span class="token function">apply</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token builtin">Promise</span><span class="token operator">&lt;</span>EnvsRaw<span class="token operator">>></span></span></span><span class="token punctuation">(</span><span class="token string">'env'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token comment">// Remainder implementation</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="미리보기-js-내보내기-처리" tabindex="-1"><a class="header-anchor" href="#미리보기-js-내보내기-처리" aria-hidden="true">#</a> 미리보기.js 내보내기 처리</h3>
<p>프리뷰.js 구성 파일을 통해 사용자는 스토리가 UI에 어떻게 렌더링되는지를 제어할 수 있습니다. 이는 데코레이터로 내보낸 것을 통해 제공됩니다. Storybook이 시작될 때, 내부 API 호출로 이러한 이름 지정된 내보내기를 가상 모듈 엔트리를 통해 변환합니다. 예를 들어, addDecorator()와 같은 것입니다. 빌더는 비슷한 구현을 제공해야 합니다. 아래는 예시입니다:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> virtualPreviewFile<span class="token punctuation">,</span> virtualStoriesFile <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./virtual-file-names'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> transformAbsPath <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./utils/transform-abs-path'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token keyword">type</span> <span class="token punctuation">{</span> ExtendedOptions <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./types'</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">async</span> <span class="token keyword">function</span> <span class="token function">generateIframeScriptCode</span><span class="token punctuation">(</span>options<span class="token operator">:</span> ExtendedOptions<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> <span class="token punctuation">{</span> presets<span class="token punctuation">,</span> frameworkPath<span class="token punctuation">,</span> framework <span class="token punctuation">}</span> <span class="token operator">=</span> options<span class="token punctuation">;</span>
  <span class="token keyword">const</span> frameworkImportPath <span class="token operator">=</span> frameworkPath <span class="token operator">||</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">@storybook/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>framework<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>

  <span class="token keyword">const</span> presetEntries <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">presets</span><span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span><span class="token string">'config'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> configEntries <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token operator">...</span>presetEntries<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span>Boolean<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">const</span> <span class="token function-variable function">absoluteFilesToImport</span> <span class="token operator">=</span> <span class="token punctuation">(</span>files<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token operator">=></span>
    files
      <span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span>el<span class="token punctuation">,</span> i<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">import </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>name <span class="token operator">?</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">* as </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>name<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">_</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>i<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> from </span><span class="token template-punctuation string">`</span></span> <span class="token operator">:</span> <span class="token string">''</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">'</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token function">transformAbsPath</span><span class="token punctuation">(</span>el<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">'</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span>
      <span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">'\n'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">const</span> <span class="token function-variable function">importArray</span> <span class="token operator">=</span> <span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> length<span class="token operator">:</span> <span class="token builtin">number</span><span class="token punctuation">)</span> <span class="token operator">=></span>
    <span class="token keyword">new</span> <span class="token class-name"><span class="token builtin">Array</span></span><span class="token punctuation">(</span>length<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">fill</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span>_<span class="token punctuation">,</span> i<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>name<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">_</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>i<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">const</span> code <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">
    // Ensure that the client API is initialized by the framework before any other iframe code
    // is loaded. That way our client-apis can assume the existence of the API+store
    import { configure } from '</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>frameworkImportPath<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">';

    import {
      addDecorator,
      addParameters,
      addArgTypesEnhancer,
      addArgsEnhancer,
      setGlobalRender
    } from '@storybook/preview-api';
    import { logger } from '@storybook/client-logger';
    </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token function">absoluteFilesToImport</span><span class="token punctuation">(</span>configEntries<span class="token punctuation">,</span> <span class="token string">'config'</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">
    import * as preview from '</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>virtualPreviewFile<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">';
    import { configStories } from '</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>virtualStoriesFile<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">';

    const configs = [</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token function">importArray</span><span class="token punctuation">(</span><span class="token string">'config'</span><span class="token punctuation">,</span> configEntries<span class="token punctuation">.</span>length<span class="token punctuation">)</span>
      <span class="token punctuation">.</span><span class="token function">concat</span><span class="token punctuation">(</span><span class="token string">'preview.default'</span><span class="token punctuation">)</span>
      <span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">].filter(Boolean)

    configs.forEach(config => {
      Object.keys(config).forEach((key) => {
        const value = config[key];
        switch (key) {
          case 'args':
          case 'argTypes': {
            return logger.warn('Invalid args/argTypes in config, ignoring.', JSON.stringify(value));
          }
          case 'decorators': {
            return value.forEach((decorator) => addDecorator(decorator, false));
          }
          case 'parameters': {
            return addParameters({ ...value }, false);
          }
          case 'render': {
            return setGlobalRender(value)
          }
          case 'globals':
          case 'globalTypes': {
            const v = {};
            v[key] = value;
            return addParameters(v, false);
          }
          case 'decorateStory':
          case 'renderToCanvas': {
            return null;
          }
          default: {
            // eslint-disable-next-line prefer-template
            return console.log(key + ' was not supported :( !');
          }
        }
      });
    })
    configStories(configure);
    </span><span class="token template-punctuation string">`</span></span><span class="token punctuation">.</span><span class="token function">trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> code<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="mdx-지원" tabindex="-1"><a class="header-anchor" href="#mdx-지원" aria-hidden="true">#</a> MDX 지원</h3>
<p>Storybook의 Docs에는 MDX를 사용하여 스토리/문서를 작성할 수 있는 기능이 포함되어 있습니다. 빌더는 또한 MDX를 해석하고 Storybook의 특수 확장 기능을 호출하는 방법을 알아야 합니다. 예를 들어:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> mdx <span class="token keyword">from</span> <span class="token string">'vite-plugin-mdx'</span><span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token punctuation">{</span> createCompiler <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@storybook/csf-tools/mdx'</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">mdxPlugin</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">mdx</span><span class="token punctuation">(</span><span class="token punctuation">(</span>filename<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> compilers <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>

    <span class="token keyword">if</span> <span class="token punctuation">(</span>filename<span class="token punctuation">.</span><span class="token function">endsWith</span><span class="token punctuation">(</span><span class="token string">'stories.mdx'</span><span class="token punctuation">)</span> <span class="token operator">||</span> filename<span class="token punctuation">.</span><span class="token function">endsWith</span><span class="token punctuation">(</span><span class="token string">'story.mdx'</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      compilers<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token function">createCompiler</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> <span class="token punctuation">{</span>
      compilers<span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="소스-코드-스니펫-생성" tabindex="-1"><a class="header-anchor" href="#소스-코드-스니펫-생성" aria-hidden="true">#</a> 소스 코드 스니펫 생성</h3>
<p>Storybook은 컴포넌트 및 이야기에 대한 추가 입력과 관련된 메타데이터를 주석으로 붙여서 대화식 컨트롤 및 문서를 자동으로 생성합니다. 현재, Webpack 로더/플러그인을 통해 제공됩니다. 빌더는 이러한 기능을 지원하기 위해 이를 다시 구현해야 합니다.</p>
<h3 id="정적-빌드-생성" tabindex="-1"><a class="header-anchor" href="#정적-빌드-생성" aria-hidden="true">#</a> 정적 빌드 생성</h3>
<p>Storybook의 핵심 기능 중 하나는 웹 호스팅 서비스에 발행할 수 있는 정적 빌드를 생성할 수 있는 능력입니다. 빌더는 비슷한 메커니즘을 제공해야 합니다. 예를 들어:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> build <span class="token keyword">as</span> viteBuild <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vite'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> stringifyProcessEnvs <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./envs'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> commonConfig <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./vite-config'</span><span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token keyword">type</span> <span class="token punctuation">{</span> EnvsRaw<span class="token punctuation">,</span> ExtendedOptions <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./types'</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">async</span> <span class="token keyword">function</span> <span class="token function">build</span><span class="token punctuation">(</span>options<span class="token operator">:</span> ExtendedOptions<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> <span class="token punctuation">{</span> presets <span class="token punctuation">}</span> <span class="token operator">=</span> options<span class="token punctuation">;</span>

  <span class="token keyword">const</span> baseConfig <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">commonConfig</span><span class="token punctuation">(</span>options<span class="token punctuation">,</span> <span class="token string">'build'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> config <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>baseConfig<span class="token punctuation">,</span>
    build<span class="token operator">:</span> <span class="token punctuation">{</span>
      outDir<span class="token operator">:</span> options<span class="token punctuation">.</span>outputDir<span class="token punctuation">,</span>
      emptyOutDir<span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
      sourcemap<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>

  <span class="token keyword">const</span> finalConfig <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">presets</span><span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span><span class="token string">'viteFinal'</span><span class="token punctuation">,</span> config<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">const</span> envsRaw <span class="token operator">=</span> <span class="token keyword">await</span> presets<span class="token punctuation">.</span><span class="token generic-function"><span class="token function">apply</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token builtin">Promise</span><span class="token operator">&lt;</span>EnvsRaw<span class="token operator">>></span></span></span><span class="token punctuation">(</span><span class="token string">'env'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// Stringify env variables after getting `envPrefix` from the final config</span>
  <span class="token keyword">const</span> envs <span class="token operator">=</span> <span class="token function">stringifyProcessEnvs</span><span class="token punctuation">(</span>envsRaw<span class="token punctuation">,</span> finalConfig<span class="token punctuation">.</span>envPrefix<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// Update `define`</span>
  finalConfig<span class="token punctuation">.</span>define <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>finalConfig<span class="token punctuation">.</span>define<span class="token punctuation">,</span>
    <span class="token operator">...</span>envs<span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>

  <span class="token keyword">await</span> <span class="token function">viteBuild</span><span class="token punctuation">(</span>finalConfig<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="개발-서버-통합" tabindex="-1"><a class="header-anchor" href="#개발-서버-통합" aria-hidden="true">#</a> 개발 서버 통합</h3>
<p>기본적으로 Storybook이 개발 모드에서 시작될 때, 내부 개발 서버에 의존합니다. 빌더는 이와 통합할 수 있어야 합니다. 예를 들어:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> createServer <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vite'</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">async</span> <span class="token keyword">function</span> <span class="token function">createViteServer</span><span class="token punctuation">(</span>options<span class="token operator">:</span> ExtendedOptions<span class="token punctuation">,</span> devServer<span class="token operator">:</span> Server<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> <span class="token punctuation">{</span> port <span class="token punctuation">}</span> <span class="token operator">=</span> options<span class="token punctuation">;</span>
  <span class="token comment">// 나머지 서버 구성</span>

  <span class="token comment">// 서버를 생성합니다.</span>
  <span class="token keyword">return</span> <span class="token function">createServer</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token comment">// 서버 구성은 여기에 작성합니다</span>
    server<span class="token operator">:</span> <span class="token punctuation">{</span>
      middlewareMode<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
      hmr<span class="token operator">:</span> <span class="token punctuation">{</span>
        port<span class="token punctuation">,</span>
        server<span class="token operator">:</span> devServer<span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="개발-서버-종료" tabindex="-1"><a class="header-anchor" href="#개발-서버-종료" aria-hidden="true">#</a> 개발 서버 종료</h3>
<p>개발자는 프로세스가 종료될 때 개발 서버를 중지할 수 있는 방법을 제공해야 합니다. 사용자 입력이나 오류를 통해서 구현할 수 있습니다. 예를 들어:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> createViteServer <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./vite-server'</span><span class="token punctuation">;</span>

<span class="token keyword">let</span> server<span class="token operator">:</span> ViteDevServer<span class="token punctuation">;</span>
<span class="token keyword">export</span> <span class="token keyword">async</span> <span class="token keyword">function</span> <span class="token function">bail</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span><span class="token keyword">void</span><span class="token operator">></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> server<span class="token operator">?.</span><span class="token function">close</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token keyword">export</span> <span class="token keyword">const</span> start<span class="token operator">:</span> ViteBuilder<span class="token punctuation">[</span><span class="token string">'start'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">{</span> options<span class="token punctuation">,</span> server<span class="token operator">:</span> devServer <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token comment">// 남은 구현 부분을 여기에 작성합니다</span>
  server <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">createViteServer</span><span class="token punctuation">(</span>options <span class="token keyword">as</span> ExtendedOptions<span class="token punctuation">,</span> devServer<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">return</span> <span class="token punctuation">{</span>
    bail<span class="token punctuation">,</span>
    totalTime<span class="token operator">:</span> process<span class="token punctuation">.</span><span class="token function">hrtime</span><span class="token punctuation">(</span>startTime<span class="token punctuation">)</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="hmr-지원" tabindex="-1"><a class="header-anchor" href="#hmr-지원" aria-hidden="true">#</a> HMR 지원</h3>
<p>개발 모드에서 실행 중일 때, 개발 서버는 변경이 발생할 때 페이지를 다시로드할 수 있어야 합니다. 변경은 이야기, 구성 요소, 또는 도우미 함수 중 어디서든 발생할 수 있습니다.</p>
<h3 id="자세한-정보" tabindex="-1"><a class="header-anchor" href="#자세한-정보" aria-hidden="true">#</a> 자세한 정보</h3>
<p>이 영역은 빠르게 개발 중이며, 관련 문서는 아직 진행 중이며 변경될 수 있습니다. 만약 빌더를 만들고 싶다면, Vite, Webpack 또는 Modern Web의 dev-server-storybook 소스 코드를 확인하여 Storybook에서 빌더를 구현하는 방법에 대해 더 알아볼 수 있습니다. 준비가 되었을 때, Storybook 커뮤니티 및 유지 보수자들과의 제안을 논의하기 위해 RFC를 열어주세요.</p>
<p>빌더에 대해 더 알아보세요</p>
<ul>
<li>Vite 빌더: Vite로 번들링</li>
<li>Webpack 빌더: Webpack으로 번들링</li>
<li>빌더 API: Storybook 빌더를 구축하기 위한 API</li>
</ul>
</div></template>
