<template><div><p>Storybook에서 여러분의 스토리들은 Storybook 웹 애플리케이션 내부의 특정 &quot;미리보기&quot; 아이프레임(캔버스 탭)에서 렌더링됩니다. 미리보기의 JavaScript 빌드 구성은 웹팩 설정에 의해 제어되지만, 여러분은 스토리들이 올바르게 렌더링되도록 직접 렌더링된 HTML을 제어하기 위해 추가적인 작업을 할 수도 있습니다.</p>
<h2 id="head에-추가하기" tabindex="-1"><a class="header-anchor" href="#head에-추가하기" aria-hidden="true">#</a> <code v-pre>head</code>에 추가하기</h2>
<p>예를 들어 미리보기 아이프레임의 <code v-pre>head</code>에 추가적인 요소를 넣어야 하는 경우, 정적 스타일시트, 글꼴 파일 등을 로드할 때 .storybook/preview-head.html이라는 파일을 생성하고 다음과 같이 태그를 추가할 수 있습니다:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token operator">&lt;</span><span class="token operator">!</span><span class="token operator">--</span> Static 디렉토리에서 제공되는 정적 파일이나 인터넷에서 제공되는 파일 가져오기 <span class="token operator">--</span><span class="token operator">></span>
<span class="token operator">&lt;</span><span class="token operator">!</span><span class="token operator">--</span> 예시<span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">main.js|ts</span><span class="token template-punctuation string">`</span></span>는 staticDirs<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'../public'</span><span class="token punctuation">]</span>로 구성되어 있고 여러분의 글꼴은 <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">public</span><span class="token template-punctuation string">`</span></span> 디렉토리 내부의 <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">fonts</span><span class="token template-punctuation string">`</span></span> 디렉토리에 있습니다 <span class="token operator">--</span><span class="token operator">></span>
<span class="token operator">&lt;</span>link rel<span class="token operator">=</span><span class="token string">"preload"</span> href<span class="token operator">=</span><span class="token string">"/fonts/my-font.woff2"</span> <span class="token operator">/</span><span class="token operator">></span>

<span class="token operator">&lt;</span><span class="token operator">!</span><span class="token operator">--</span> 또는 사용자 지정 head 태그 JavaScript를 로드할 수도 있습니다<span class="token operator">:</span> <span class="token operator">--</span><span class="token operator">></span>

<span class="token operator">&lt;</span>script src<span class="token operator">=</span><span class="token string">"https://use.typekit.net/xxxyyy.js"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>script<span class="token operator">></span>
<span class="token operator">&lt;</span>script<span class="token operator">></span>
  <span class="token keyword">try</span> <span class="token punctuation">{</span>
    Typekit<span class="token punctuation">.</span><span class="token function">load</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>e<span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
<span class="token operator">&lt;</span><span class="token operator">/</span>script<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>그러나 main.js 파일에 정의된 프리셋을 사용하여 미리보기 헤드 HTML을 프로그래밍적으로 수정하는 것도 가능합니다. 더 많은 정보를 얻으려면 프리셋 설명서를 읽어보세요.</p>
<h2 id="body에-추가하기" tabindex="-1"><a class="header-anchor" href="#body에-추가하기" aria-hidden="true">#</a> <code v-pre>body</code>에 추가하기</h2>
<p>가끔은 <code v-pre>body</code>에 다른 태그를 추가해야 할 수도 있습니다. 사용자 지정 콘텐츠 루트를 추가하는 데 도움이 됩니다.</p>
<p>.storybook 디렉토리 내에 preview-body.html이라는 파일을 만들고 다음과 같이 태그를 추가함으로써 이를 수행할 수 있습니다:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token operator">&lt;</span>div id<span class="token operator">=</span><span class="token string">"custom-root"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>만약 rem이나 em과 같은 상대 크기를 사용하는 프로젝트라면, preview-body.html에 스타일 태그를 추가하여 기본 글꼴 크기를 업데이트할 수 있습니다:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token operator">&lt;</span>style<span class="token operator">></span>
  html <span class="token punctuation">{</span>
    font<span class="token operator">-</span>size<span class="token operator">:</span> 15px<span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token operator">&lt;</span><span class="token operator">/</span>style<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>미리보기 헤드 HTML 태그를 사용자 정의할 수 있는 것처럼, 동일한 단계를 따라 미리보기 본문을 사용자 정의할 수도 있습니다. 이를 수행하는 방법에 대한 자세한 정보는 프리셋 문서를 참고하세요.```</p>
</div></template>
