<template><div><h1 id="웹사이트-구글-검색-되게-하는-방법" tabindex="-1"><a class="header-anchor" href="#웹사이트-구글-검색-되게-하는-방법" aria-hidden="true">#</a> 웹사이트 구글 검색 되게 하는 방법</h1>
<p>아무리 사이트를 잘 만들어두어도 아무도 들어오지 않는다면 소용이 없겠죠?
잘 만든 사이트를 구글 검색에 노출이 되어 아래와 같이 유입을 만들 수 있는 방법을 정리했습니다.</p>
<p><img src="@source/docs/ETC/2022-11-28-웹사이트-구글-검색-되게-하는-방법/img/2.png" alt=""></p>
<h2 id="search-console" tabindex="-1"><a class="header-anchor" href="#search-console" aria-hidden="true">#</a> Search Console</h2>
<p>구글 검색 결과에 노출이 되려면 <a href="https://search.google.com/search-console/about" target="_blank" rel="noopener noreferrer">서치콘솔(Search Condsole)<ExternalLinkIcon/></a>에 사이트를 등록해야하는데요.</p>
<p><img src="@source/docs/ETC/2022-11-28-웹사이트-구글-검색-되게-하는-방법/img/1.jpg" alt=""></p>
<p>사이트에 방문해서 시작하기 버튼을 눌러줍니다.</p>
<img src="@source/docs/ETC/2022-11-28-웹사이트-구글-검색-되게-하는-방법/img/3.png" width="500">
<p>좌측 속성 검색 버튼을 누르면 위와 같이 창이 나오는데 여기서 '속성추가'를 눌러줍니다.</p>
<img src="@source/docs/ETC/2022-11-28-웹사이트-구글-검색-되게-하는-방법/img/4.png" width="500">
<p>여기서 도메인이 아닌 'URL 접두어'의 입력창에 보유하신 사이트 주소를 입력하고 계속 버튼을 눌러줍니다.</p>
<img src="@source/docs/ETC/2022-11-28-웹사이트-구글-검색-되게-하는-방법/img/5.png" width="500">
<p>검토 후에 소유권 확인 창이 나오는데요. 본인이 소유한 사이트가 맞는지 소유권 확인 절차가 필요합니다.
소유권 확인 방법에는 HTML파일을 사이트에 추가하는 것이 있고, 그 외에도
HTML 태그를 추가하거나 구글 애널리틱스(GA)계정을 연동하거나 여러 방법이 존재합니다.</p>
<p>저는 가장 간단한 HTML태그을 웹사이트에 추가하는 방식으로 하겠습니다.</p>
<p>저는 Nextjs로 제작한 사이트라 아래와 같이 <code v-pre>&lt;Head&gt;</code> 태그 사이에 넣어주었습니다.</p>
<p><img src="@source/docs/ETC/2022-11-28-웹사이트-구글-검색-되게-하는-방법/img/6.png" alt=""></p>
<div class="language-tsx ext-tsx line-numbers-mode"><pre v-pre class="language-tsx"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token class-name">Head</span></span><span class="token punctuation">></span></span><span class="token plain-text">
  </span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span><span class="token plain-text">thumbnail maker</span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span><span class="token plain-text">
  </span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>google-site-verification<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>iBrZvJIvnHVubE85EUieSyBXctuRY79ZcktaVjMG_rQ<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span><span class="token plain-text">
  </span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>description<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>Generated by create next app<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span><span class="token plain-text">
  </span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>icon<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/favicon.ico<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span><span class="token plain-text">
</span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token class-name">Head</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>정적인 meta태그 추가는 이렇게 그냥 한줄 추가하면 되지만
가끔씩 동적인 meta태그를 추가해야하는 상황이 있는데요.
해당 내용은 아래 포스팅에서 확인하실 수 있습니다.</p>
<p>위 메타 태그를 추가한 뒤 확인 버튼을 클릭하면</p>
<img src="@source/docs/ETC/2022-11-28-웹사이트-구글-검색-되게-하는-방법/img/7.png" width="500">
<img src="@source/docs/ETC/2022-11-28-웹사이트-구글-검색-되게-하는-방법/img/8.png" width="500">
<p>확인 후에 아래와 같이 나오는 것을 보실 수 있습니다.</p>
<img src="@source/docs/ETC/2022-11-28-웹사이트-구글-검색-되게-하는-방법/img/9.png" width="500">
<p>Nextjs 에서 sitemap 추가 및 구글 검색에 잘 걸리도록하는 SEO 셋팅 방법에 대해서 추후 다뤄보도록 하겠습니다.</p>
</div></template>
